/**
 * ULID generator (Crockford base32, 26 chars).
 *
 * Worker mirror of `manicbot/admin-app/src/lib/ulid.ts`. The two MUST stay
 * byte-compatible — a ULID generated by the admin-app and one generated by
 * the Worker need to sort against each other identically (chronological
 * order of thread_messages within a thread).
 *
 * Format: TTTTTTTTTTRRRRRRRRRRRRRRRR
 *   T (10) — timestamp ms (48 bits)
 *   R (16) — random (80 bits)
 */

const ALPHABET = '0123456789ABCDEFGHJKMNPQRSTVWXYZ';

function encodeTime(ms, len) {
  let out = '';
  let value = ms;
  for (let i = len - 1; i >= 0; i--) {
    const mod = value % 32;
    out = ALPHABET[mod] + out;
    value = (value - mod) / 32;
  }
  return out;
}

function encodeRandom(len) {
  const bytes = new Uint8Array(len);
  crypto.getRandomValues(bytes);
  let out = '';
  for (let i = 0; i < len; i++) {
    out += ALPHABET[bytes[i] % 32];
  }
  return out;
}

/**
 * Generate a ULID. Optional timestamp lets tests pin chronological order.
 * @param {number=} timestamp - ms since epoch
 * @returns {string} 26-char ULID
 */
export function ulid(timestamp) {
  const ms = timestamp == null ? Date.now() : timestamp;
  return encodeTime(ms, 10) + encodeRandom(16);
}

/** @param {string} s */
export function isUlid(s) {
  if (typeof s !== 'string' || s.length !== 26) return false;
  for (let i = 0; i < 26; i++) {
    if (ALPHABET.indexOf(s[i]) === -1) return false;
  }
  return true;
}
