-- 0078_notification_prefs.sql
-- Adds per-user notification preferences as a JSON blob on web_users.
--
-- Shape:
--   {
--     "categories": {
--       "appointment": { "inapp": true,  "push": true },
--       "support":     { "inapp": true,  "push": true },
--       "birthday":    { "inapp": true,  "push": false },
--       "platform":    { "inapp": true,  "push": true },
--       "master":      { "inapp": true,  "push": true },
--       "reminder":    { "inapp": true,  "push": true },
--       "messenger":   { "inapp": true,  "push": true },
--       "billing":     { "inapp": true,  "push": true },
--       "marketing":   { "inapp": true,  "push": false }
--     }
--   }
--
-- NULL means "use defaults" (see lib/notifications/prefs.ts).
-- A missing category in the JSON also resolves to default-on.
-- Writers consult prefs at fan-out time and skip the channel when the
-- category is opted-out; the partial UNIQUE on user_notifications still
-- dedups in-app rows on retry as before.
--
-- NOTE: This file was originally filed as 0077_notification_prefs.sql, which
-- conflicted with 0077_service_categories.sql and was renamed in PR #198.
-- Production D1 already has this column (applied under the old filename).
-- Using ADD COLUMN IF NOT EXISTS (SQLite 3.37+ / D1) so this migration is
-- idempotent whether or not the column was applied under the previous name.
ALTER TABLE web_users ADD COLUMN IF NOT EXISTS notification_prefs TEXT;
