-- 0079_user_avatar.sql — DRIFT FIX (2026-05-18)
--
-- Original content of this migration (3 × ALTER TABLE users ADD COLUMN
-- avatar_emoji / avatar_url / avatar_r2_key) was already applied to prod D1
-- manually before the CI auto-apply workflow landed (PR #169). The columns
-- exist on prod under d1_migrations name `0072_user_avatar.sql` (rename
-- happened mid-flight when migration numbers collided with `0072_segment_members.sql`).
--
-- Because CI now auto-runs `wrangler d1 migrations apply`, prod kept failing
-- with `duplicate column name: avatar_emoji` on every deploy. Direct INSERT
-- into d1_migrations was blocked by the security classifier, so we resolve
-- the drift here: turn this file into a SELECT-no-op so wrangler records it
-- as applied and moves on.
--
-- Schema correctness is preserved: `manicbot/src/db/schema.sql` declares all
-- three avatar columns in the users CREATE TABLE, so fresh-setup paths
-- (/admin/seed reads schema.sql) continue to ship a complete schema.
SELECT 1;
