# Multi-tenant ManicBot (root worker)
name = "manicbot"
main = "worker.js"
compatibility_date = "2025-01-01"

[triggers]
crons = ["*/15 * * * *"]

[[kv_namespaces]]
binding = "MANICBOT"
id = "62a7d16805e742918a82184e879537cc"
