"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import type { MouseEvent as RMouseEvent, WheelEvent as RWheelEvent } from "react";
import { api } from "~/trpc/react";
import { Shell } from "~/components/layout/Shell";
import {
  Network, RefreshCw, ZoomIn, ZoomOut, Maximize2, AlertTriangle, Loader2, ShieldCheck,
} from "lucide-react";

const ICONBTN =
  "inline-flex items-center justify-center w-8 h-8 rounded-lg border border-slate-200 " +
  "dark:border-white/10 text-slate-600 dark:text-slate-300 hover:bg-slate-100 " +
  "dark:hover:bg-white/5 transition";

// Monotonic id so each mermaid.render() call gets a fresh element id.
let renderSeq = 0;

/**
 * God-Mode DB architecture map. Pulls the auto-generated, domain-grouped
 * top-down Mermaid flowchart from `system.getArchitectureDiagram` (admin-only)
 * and renders it client-side with wheel-zoom + drag-pan, fitting the whole
 * diagram to the viewport on load. `mermaid` is loaded lazily (this route only).
 */
export default function ArchitectureClient() {
  const { data, isLoading, error, refetch, isFetching } =
    api.system.getArchitectureDiagram.useQuery(undefined, { staleTime: 5 * 60_000 });

  const containerRef = useRef<HTMLDivElement>(null);
  const hostRef = useRef<HTMLDivElement>(null);
  const [zoom, setZoom] = useState(1);
  const [pan, setPan] = useState({ x: 24, y: 16 });
  const [renderError, setRenderError] = useState<string | null>(null);
  const [rendering, setRendering] = useState(false);
  const drag = useRef<{ x: number; y: number; px: number; py: number } | null>(null);

  // Scale + center the rendered SVG so the whole map fits the viewport.
  const fitToView = useCallback(() => {
    const host = hostRef.current;
    const cont = containerRef.current;
    if (!host || !cont) return;
    const svgEl = host.querySelector("svg");
    if (!svgEl) return;
    let sW = 0;
    let sH = 0;
    const vb = svgEl.viewBox?.baseVal;
    if (vb && vb.width) {
      sW = vb.width;
      sH = vb.height;
    } else {
      const r = svgEl.getBoundingClientRect();
      sW = r.width;
      sH = r.height;
    }
    if (!sW || !sH) return;
    const cW = cont.clientWidth;
    const cH = cont.clientHeight;
    const z = Math.max(0.1, Math.min(1.5, Math.min(cW / sW, cH / sH) * 0.94));
    setZoom(z);
    setPan({ x: Math.max(8, (cW - sW * z) / 2), y: 14 });
  }, []);

  useEffect(() => {
    const mermaidText = data?.mermaid;
    if (!mermaidText || !hostRef.current) return;
    let cancelled = false;
    setRenderError(null);
    setRendering(true);
    void (async () => {
      try {
        // @ts-ignore — `mermaid` is a real dependency (package.json); it is only
        // absent from the symlinked worktree node_modules used for local checks.
        const mermaid = (await import("mermaid")).default;
        const isDark =
          typeof document !== "undefined" &&
          document.documentElement.classList.contains("dark");
        mermaid.initialize({
          startOnLoad: false,
          // Our diagram is generated by us from schema.sql (no user input), so
          // 'loose' is safe and lets node labels use <b>/<i>/<br/> for the
          // Russian domain titles + descriptions + per-table line breaks.
          securityLevel: "loose",
          maxTextSize: 500_000,
          flowchart: { htmlLabels: true, curve: "basis", nodeSpacing: 36, rankSpacing: 70 },
          theme: isDark ? "dark" : "default",
        });
        const { svg } = await mermaid.render(`erd-${++renderSeq}`, mermaidText);
        if (cancelled || !hostRef.current) return;
        hostRef.current.innerHTML = svg;
        // Let the SVG attach to the DOM, then fit it to the viewport.
        requestAnimationFrame(() => {
          if (!cancelled) fitToView();
        });
      } catch (e) {
        if (!cancelled) setRenderError(e instanceof Error ? e.message : String(e));
      } finally {
        if (!cancelled) setRendering(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [data?.mermaid, fitToView]);

  const onWheel = useCallback((e: RWheelEvent) => {
    setZoom((z) => Math.min(4, Math.max(0.1, z * (e.deltaY < 0 ? 1.12 : 0.89))));
  }, []);
  const onMouseDown = (e: RMouseEvent) => {
    drag.current = { x: e.clientX, y: e.clientY, px: pan.x, py: pan.y };
  };
  const onMouseMove = (e: RMouseEvent) => {
    if (!drag.current) return;
    setPan({
      x: drag.current.px + (e.clientX - drag.current.x),
      y: drag.current.py + (e.clientY - drag.current.y),
    });
  };
  const endDrag = () => {
    drag.current = null;
  };

  const generatedLabel =
    data?.source === "generated" && data?.generatedAt
      ? new Date(data.generatedAt).toLocaleString("ru-RU")
      : null;

  return (
    <Shell>
      <div className="p-4 sm:p-6 space-y-4">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div className="flex items-center gap-2">
            <Network className="w-5 h-5 text-sky-400" />
            <h1 className="text-lg font-semibold text-slate-900 dark:text-white">
              Архитектура — карта базы данных
            </h1>
          </div>
          <div className="flex items-center gap-1.5">
            <button onClick={() => setZoom((z) => Math.min(4, z * 1.2))} className={ICONBTN} title="Приблизить">
              <ZoomIn className="w-4 h-4" />
            </button>
            <button onClick={() => setZoom((z) => Math.max(0.1, z * 0.83))} className={ICONBTN} title="Отдалить">
              <ZoomOut className="w-4 h-4" />
            </button>
            <button onClick={fitToView} className={ICONBTN} title="Вписать в экран">
              <Maximize2 className="w-4 h-4" />
            </button>
            <button onClick={() => void refetch()} className={ICONBTN} title="Обновить">
              <RefreshCw className={`w-4 h-4 ${isFetching ? "animate-spin" : ""}`} />
            </button>
          </div>
        </div>

        <div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-xs text-slate-500 dark:text-slate-400">
          <span className="inline-flex items-center gap-1">
            <ShieldCheck className="w-3.5 h-3.5 text-emerald-500" /> Приватно — только God Mode
          </span>
          {typeof data?.tableCount === "number" && data.tableCount > 0 && (
            <span>
              Таблиц: {data.tableCount}
              {typeof data?.domainCount === "number" && data.domainCount > 0
                ? ` · Доменов: ${data.domainCount}`
                : ""}
            </span>
          )}
          {generatedLabel ? (
            <span>Обновлено на деплое: {generatedLabel}</span>
          ) : data?.source === "stub" ? (
            <span className="text-amber-500">
              Заглушка — реальная карта появится после следующего деплоя admin-app
            </span>
          ) : null}
        </div>

        {error ? (
          <div className="rounded-xl border border-red-200 dark:border-red-500/20 bg-red-50 dark:bg-red-500/5 p-6 text-sm text-red-600 dark:text-red-400">
            Нет доступа или ошибка загрузки карты.
          </div>
        ) : isLoading ? (
          <div className="flex items-center gap-2 p-6 text-sm text-slate-400">
            <Loader2 className="w-4 h-4 animate-spin" /> Загрузка…
          </div>
        ) : (
          <div
            ref={containerRef}
            className="relative overflow-hidden rounded-xl border border-slate-200 dark:border-white/10 bg-white dark:bg-slate-900 h-[74vh] cursor-grab active:cursor-grabbing select-none"
            onWheel={onWheel}
            onMouseDown={onMouseDown}
            onMouseMove={onMouseMove}
            onMouseUp={endDrag}
            onMouseLeave={endDrag}
          >
            {(rendering || isFetching) && (
              <div className="absolute top-2 left-2 z-10 inline-flex items-center gap-1 text-xs text-slate-400">
                <Loader2 className="w-3.5 h-3.5 animate-spin" /> Рендер…
              </div>
            )}
            {renderError && (
              <div className="absolute inset-0 z-10 grid place-items-center p-6 text-center text-sm text-red-500">
                <div>
                  <AlertTriangle className="w-5 h-5 mx-auto mb-2" />
                  Не удалось отрисовать карту:
                  <br />
                  <code className="text-xs break-all">{renderError}</code>
                </div>
              </div>
            )}
            <div
              style={{
                transform: `translate(${pan.x}px, ${pan.y}px) scale(${zoom})`,
                transformOrigin: "0 0",
              }}
              className="will-change-transform"
            >
              <div ref={hostRef} className="[&_svg]:max-w-none" />
            </div>
          </div>
        )}

        <p className="text-xs text-slate-400">
          Колёсико — масштаб, перетаскивание — панорама, кнопка «вписать» — по размеру. Карта
          пересобирается из <code>schema.sql</code> на каждом деплое admin-app и видна только тебе.
          Имена таблиц — реальные идентификаторы из кода; домены и описания — на русском.
        </p>
      </div>
    </Shell>
  );
}
