/** Per-language label sets for navigation items, groups, and role info. */
export const NAV_LABELS: Record<string, Record<string, string>> = {
  ru: {
    // God Mode groups
    "Overview": "Обзор",
    "Management": "Управление",
    "Platform": "Платформа",
    // God Mode items
    "Dashboard": "Домой",
    "Users": "Пользователи",
    "Tenants": "Салоны",
    "Appointments": "Записи",
    "Inbox": "Входящие",
    "Platform tickets": "Тикеты платформы",
    "Role Requests": "Заявки на роль",
    "Leads": "Заявки",
    "Agents": "Агенты",
    "Billing": "Биллинг",
    "Events": "События",
    "Errors": "Ошибки",
    "System": "Система",
    "Providers": "Провайдеры",
    "Settings": "Настройки",
    "Plugins": "Плагины",
    "Marketing": "Маркетинг",
    "Marketing Center": "Центр маркетинга",
    "Messages": "Сообщения",
    // Salon nav
    "Services": "Услуги",
    "Masters": "Мастера",
    "Clients": "Клиенты",
    "Channels": "Каналы",
    // Master nav
    "Today": "Сегодня",
    "Schedule": "Расписание",
    "Earnings": "Доходы",
    "Profile": "Профиль",
    "Reviews": "Отзывы",
    "Analytics": "Аналитика",
    "PublicProfile": "Публичный профиль",
    // Support
    "Tickets": "Тикеты",
    // Role info
    "Admin Panel": "Панель администратора",
    "God Mode": "Админ",
    "My Salon": "Мой салон",
    "My Schedule": "Моё расписание",
    "Master": "Мастер",
    "Support": "Поддержка",
    "Tech Support": "Тех. поддержка",
    "Agent Hub": "Центр агентов",
    "Logout": "Выйти",
    "Collapse": "Свернуть",
    "LogoutConfirmTitle": "Выйти из аккаунта?",
    "LogoutConfirmDesc": "Вы уверены, что хотите выйти?",
    "Cancel": "Отмена",
  },
  ua: {
    "Overview": "Огляд",
    "Management": "Управління",
    "Platform": "Платформа",
    "Dashboard": "Додому",
    "Users": "Користувачі",
    "Tenants": "Салони",
    "Appointments": "Записи",
    "Inbox": "Вхідні",
    "Platform tickets": "Тикети платформи",
    "Role Requests": "Заявки на роль",
    "Leads": "Заявки",
    "Agents": "Агенти",
    "Billing": "Білінг",
    "Events": "Події",
    "Errors": "Помилки",
    "System": "Система",
    "Providers": "Провайдери",
    "Settings": "Налаштування",
    "Plugins": "Плагіни",
    "Marketing": "Маркетинг",
    "Marketing Center": "Центр маркетингу",
    "Messages": "Повідомлення",
    "Services": "Послуги",
    "Masters": "Майстри",
    "Clients": "Клієнти",
    "Channels": "Канали",
    "Today": "Сьогодні",
    "Schedule": "Розклад",
    "Earnings": "Доходи",
    "Profile": "Профіль",
    "Reviews": "Відгуки",
    "Analytics": "Аналітика",
    "PublicProfile": "Публічний профіль",
    "Tickets": "Тікети",
    "Admin Panel": "Панель адміністратора",
    "God Mode": "Адмін",
    "My Salon": "Мій салон",
    "My Schedule": "Мій розклад",
    "Master": "Майстер",
    "Support": "Підтримка",
    "Tech Support": "Тех. підтримка",
    "Agent Hub": "Центр агентів",
    "Logout": "Вийти",
    "Collapse": "Згорнути",
    "LogoutConfirmTitle": "Вийти з акаунту?",
    "LogoutConfirmDesc": "Ви впевнені, що хочете вийти?",
    "Cancel": "Скасувати",
  },
  pl: {
    "Overview": "Przegląd",
    "Management": "Zarządzanie",
    "Platform": "Platforma",
    "Dashboard": "Strona główna",
    "Users": "Użytkownicy",
    "Tenants": "Salony",
    "Appointments": "Wizyty",
    "Inbox": "Skrzynka",
    "Platform tickets": "Zgłoszenia platformy",
    "Role Requests": "Wnioski o rolę",
    "Leads": "Zgłoszenia leadów",
    "Agents": "Agenci",
    "Billing": "Płatności",
    "Events": "Zdarzenia",
    "Errors": "Błędy",
    "System": "System",
    "Providers": "Dostawcy",
    "Settings": "Ustawienia",
    "Plugins": "Wtyczki",
    "Marketing": "Marketing",
    "Marketing Center": "Centrum marketingu",
    "Messages": "Wiadomości",
    "Services": "Usługi",
    "Masters": "Mistrzowie",
    "Clients": "Klienci",
    "Channels": "Kanały",
    "Today": "Dziś",
    "Schedule": "Harmonogram",
    "Earnings": "Zarobki",
    "Profile": "Profil",
    "Reviews": "Opinie",
    "Analytics": "Analityka",
    "PublicProfile": "Profil publiczny",
    "Tickets": "Zgłoszenia",
    "Admin Panel": "Panel administratora",
    "God Mode": "Admin",
    "My Salon": "Mój salon",
    "My Schedule": "Mój harmonogram",
    "Master": "Mistrz",
    "Support": "Wsparcie",
    "Tech Support": "Wsparcie tech.",
    "Agent Hub": "Centrum agentów",
    "Logout": "Wyloguj",
    "Collapse": "Zwiń",
    "LogoutConfirmTitle": "Wylogować się?",
    "LogoutConfirmDesc": "Czy na pewno chcesz się wylogować?",
    "Cancel": "Anuluj",
  },
  en: {
    "Overview": "Overview",
    "Management": "Management",
    "Platform": "Platform",
    "Dashboard": "Home",
    "Users": "Users",
    "Tenants": "Salons",
    "Appointments": "Appointments",
    "Inbox": "Inbox",
    "Platform tickets": "Platform tickets",
    "Role Requests": "Role Requests",
    "Leads": "Leads",
    "Agents": "Agents",
    "Billing": "Billing",
    "Events": "Events",
    "Errors": "Errors",
    "System": "System",
    "Providers": "Providers",
    "Settings": "Settings",
    "Plugins": "Plugins",
    "Marketing": "Marketing",
    "Marketing Center": "Marketing Center",
    "Messages": "Messages",
    "Services": "Services",
    "Masters": "Masters",
    "Clients": "Clients",
    "Channels": "Channels",
    "Today": "Today",
    "Schedule": "Schedule",
    "Earnings": "Earnings",
    "Profile": "Profile",
    "Reviews": "Reviews",
    "Analytics": "Analytics",
    "PublicProfile": "Public Profile",
    "Tickets": "Tickets",
    "Admin Panel": "Admin Panel",
    "God Mode": "Admin",
    "My Salon": "My Salon",
    "My Schedule": "My Schedule",
    "Master": "Master",
    "Support": "Support",
    "Tech Support": "Tech Support",
    "Agent Hub": "Agent Hub",
    "Logout": "Sign out",
    "Collapse": "Collapse",
    "LogoutConfirmTitle": "Sign out?",
    "LogoutConfirmDesc": "Are you sure you want to sign out?",
    "Cancel": "Cancel",
  },
};

export function tNav(key: string, lang: string): string {
  return NAV_LABELS[lang]?.[key] ?? NAV_LABELS["ru"]?.[key] ?? key;
}
