/**
 * Architecture ERD generator (build-time, private).
 *
 * Parses the canonical D1 schema (`manicbot/src/db/schema.sql`) and emits a
 * Mermaid `erDiagram` into `src/server/_generated/erd.generated.ts`, which is
 * then embedded into the admin-app server bundle and served ONLY through the
 * God-Mode `system.getArchitectureDiagram` procedure.
 *
 * Why schema.sql (not Drizzle introspection): it is the deployed source of
 * truth, kept in sync with schema.ts by the `check-schema-tables` CI gate, and
 * needs no TypeScript loader — plain Node, zero extra deps.
 *
 * Run automatically by the CI "Generate architecture ERD" step before the
 * admin-app build. The committed `erd.generated.ts` stays a STUB; the real
 * output is produced ephemerally in CI and never committed (keeps the diagram
 * out of the public repo). Set ERD_OUT to write elsewhere (local verification).
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const SCHEMA = resolve(here, "../../src/db/schema.sql");
const OUT = process.env.ERD_OUT || resolve(here, "../src/server/_generated/erd.generated.ts");

const unquote = (s) => s.trim().replace(/^["`[]/, "").replace(/["`\]]$/, "");
const cleanName = (s) => unquote(s).replace(/[^A-Za-z0-9_]/g, "_");
const cleanType = (s) =>
  (String(s || "text").trim().split(/[\s(]/)[0] || "text")
    .replace(/[^A-Za-z0-9_]/g, "_")
    .toLowerCase() || "text";

let sql = readFileSync(SCHEMA, "utf8");
sql = sql.replace(/\/\*[\s\S]*?\*\//g, "").replace(/--[^\n]*/g, "");

const tables = [];
// Matches `CREATE TABLE [IF NOT EXISTS] name (` — note `CREATE VIRTUAL TABLE`
// (FTS) does not match `create\s+table` and is intentionally skipped.
const re = /create\s+table\s+(?:if\s+not\s+exists\s+)?([`"[]?[A-Za-z0-9_]+[`"\]]?)\s*\(/gi;
let m;
while ((m = re.exec(sql))) {
  const name = cleanName(m[1]);
  // Walk balanced parens to find the table body.
  let depth = 0;
  let end = -1;
  for (let j = re.lastIndex - 1; j < sql.length; j++) {
    const ch = sql[j];
    if (ch === "(") depth++;
    else if (ch === ")") {
      depth--;
      if (depth === 0) { end = j; break; }
    }
  }
  if (end === -1) continue;
  const body = sql.slice(re.lastIndex, end);

  // Split the body on top-level commas only.
  const parts = [];
  let d = 0;
  let cur = "";
  for (const ch of body) {
    if (ch === "(") { d++; cur += ch; }
    else if (ch === ")") { d--; cur += ch; }
    else if (ch === "," && d === 0) { parts.push(cur); cur = ""; }
    else cur += ch;
  }
  if (cur.trim()) parts.push(cur);

  const cols = [];
  const fks = [];
  const pkCols = new Set();
  for (const raw of parts) {
    const line = raw.trim();
    if (!line) continue;
    const upper = line.toUpperCase();
    if (upper.startsWith("PRIMARY KEY")) {
      const inner = line.match(/\(([^)]*)\)/);
      if (inner) inner[1].split(",").forEach((c) => pkCols.add(cleanName(c)));
      continue;
    }
    if (upper.startsWith("FOREIGN KEY")) {
      const ref = line.match(/references\s+([`"[]?[A-Za-z0-9_]+[`"\]]?)/i);
      if (ref) fks.push(cleanName(ref[1]));
      continue;
    }
    if (upper.startsWith("UNIQUE") || upper.startsWith("CHECK") || upper.startsWith("CONSTRAINT")) continue;
    const tok = line.match(/^([`"[]?[A-Za-z0-9_]+[`"\]]?)\s+([\s\S]*)$/);
    if (!tok) continue;
    const colName = cleanName(tok[1]);
    const rest = tok[2];
    if (/\bprimary\s+key\b/i.test(rest)) pkCols.add(colName);
    const inlineRef = rest.match(/references\s+([`"[]?[A-Za-z0-9_]+[`"\]]?)/i);
    if (inlineRef) fks.push(cleanName(inlineRef[1]));
    cols.push({ name: colName, type: cleanType(rest) });
  }
  for (const c of cols) c.pk = pkCols.has(c.name);
  tables.push({ name, cols, fks: [...new Set(fks)].filter((f) => f && f !== name) });
}

tables.sort((a, b) => a.name.localeCompare(b.name));
const known = new Set(tables.map((t) => t.name));

const lines = ["erDiagram"];
for (const t of tables) {
  lines.push(`  ${t.name} {`);
  for (const c of t.cols) lines.push(`    ${c.type} ${c.name}${c.pk ? " PK" : ""}`);
  lines.push("  }");
}
const seenRel = new Set();
for (const t of tables) {
  for (const to of t.fks) {
    if (!known.has(to)) continue;
    const key = `${to}->${t.name}`;
    if (seenRel.has(key)) continue;
    seenRel.add(key);
    lines.push(`  ${to} ||--o{ ${t.name} : fk`);
  }
}
const mermaid = lines.join("\n");

const file = `/* AUTO-GENERATED by scripts/gen-erd.mjs from manicbot/src/db/schema.sql.
   Do not hand-edit; do not commit a generated (non-stub) copy. Served privately
   via system.getArchitectureDiagram (God Mode). */
export const ERD_MERMAID = ${JSON.stringify(mermaid)};

export const ERD_META: {
  generatedAt: string | null;
  tableCount: number;
  source: "stub" | "generated";
} = {
  generatedAt: ${JSON.stringify(new Date().toISOString())},
  tableCount: ${tables.length},
  source: "generated",
};
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, file);
console.log(`gen-erd: ${tables.length} tables, ${seenRel.size} relations, ${mermaid.length} chars -> ${OUT}`);
